<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("DELETE FROM `atl_pais` WHERE `nombre` = 'Argentina';");

        DB::statement("INSERT INTO `atl_pais` (`id`, `nombre`)
                        VALUES
                            (1, 'Afganistán'),
                            (2, 'Islas Gland'),
                            (3, 'Albania'),
                            (4, 'Alemania'),
                            (5, 'Andorra'),
                            (6, 'Angola'),
                            (7, 'Anguilla'),
                            (8, 'Antártida'),
                            (9, 'Antigua y Barbuda'),
                            (10, 'Antillas Holandesas'),
                            (11, 'Arabia Saudí'),
                            (12, 'Argelia'),
                            (13, 'Argentina'),
                            (14, 'Armenia'),
                            (15, 'Aruba'),
                            (16, 'Australia'),
                            (17, 'Austria'),
                            (18, 'Azerbaiyán'),
                            (19, 'Bahamas'),
                            (20, 'Bahréin'),
                            (21, 'Bangladesh'),
                            (22, 'Barbados'),
                            (23, 'Bielorrusia'),
                            (24, 'Bélgica'),
                            (25, 'Belice'),
                            (26, 'Benin'),
                            (27, 'Bermudas'),
                            (28, 'Bhután'),
                            (29, 'Bolivia'),
                            (30, 'Bosnia y Herzegovina'),
                            (31, 'Botsuana'),
                            (32, 'Isla Bouvet'),
                            (33, 'Brasil'),
                            (34, 'Brunéi'),
                            (35, 'Bulgaria'),
                            (36, 'Burkina Faso'),
                            (37, 'Burundi'),
                            (38, 'Cabo Verde'),
                            (39, 'Islas Caimán'),
                            (40, 'Camboya'),
                            (41, 'Camerún'),
                            (42, 'Canadá'),
                            (43, 'República Centroafricana'),
                            (44, 'Chad'),
                            (45, 'República Checa'),
                            (46, 'Chile'),
                            (47, 'China'),
                            (48, 'Chipre'),
                            (49, 'Isla de Navidad'),
                            (50, 'Ciudad del Vaticano'),
                            (51, 'Islas Cocos'),
                            (52, 'Colombia'),
                            (53, 'Comoras'),
                            (54, 'República Democrática del Congo'),
                            (55, 'Congo'),
                            (56, 'Islas Cook'),
                            (57, 'Corea del Norte'),
                            (58, 'Corea del Sur'),
                            (59, 'Costa de Marfil'),
                            (60, 'Costa Rica'),
                            (61, 'Croacia'),
                            (62, 'Cuba'),
                            (63, 'Dinamarca'),
                            (64, 'Dominica'),
                            (65, 'República Dominicana'),
                            (66, 'Ecuador'),
                            (67, 'Egipto'),
                            (68, 'El Salvador'),
                            (69, 'Emiratos Árabes Unidos'),
                            (70, 'Eritrea'),
                            (71, 'Eslovaquia'),
                            (72, 'Eslovenia'),
                            (73, 'España'),
                            (74, 'Islas ultramarinas de Estados Unidos'),
                            (75, 'Estados Unidos'),
                            (76, 'Estonia'),
                            (77, 'Etiopía'),
                            (78, 'Islas Feroe'),
                            (79, 'Filipinas'),
                            (80, 'Finlandia'),
                            (81, 'Fiyi'),
                            (82, 'Francia'),
                            (83, 'Gabón'),
                            (84, 'Gambia'),
                            (85, 'Georgia'),
                            (86, 'Islas Georgias del Sur y Sandwich del Sur'),
                            (87, 'Ghana'),
                            (88, 'Gibraltar'),
                            (89, 'Granada'),
                            (90, 'Grecia'),
                            (91, 'Groenlandia'),
                            (92, 'Guadalupe'),
                            (93, 'Guam'),
                            (94, 'Guatemala'),
                            (95, 'Guayana Francesa'),
                            (96, 'Guinea'),
                            (97, 'Guinea Ecuatorial'),
                            (98, 'Guinea-Bissau'),
                            (99, 'Guyana'),
                            (100, 'Haití'),
                            (101, 'Islas Heard y McDonald'),
                            (102, 'Honduras'),
                            (103, 'Hong Kong'),
                            (104, 'Hungría'),
                            (105, 'India'),
                            (106, 'Indonesia'),
                            (107, 'Irán'),
                            (108, 'Iraq'),
                            (109, 'Irlanda'),
                            (110, 'Islandia'),
                            (111, 'Israel'),
                            (112, 'Italia'),
                            (113, 'Jamaica'),
                            (114, 'Japón'),
                            (115, 'Jordania'),
                            (116, 'Kazajstán'),
                            (117, 'Kenia'),
                            (118, 'Kirguistán'),
                            (119, 'Kiribati'),
                            (120, 'Kuwait'),
                            (121, 'Laos'),
                            (122, 'Lesotho'),
                            (123, 'Letonia'),
                            (124, 'Líbano'),
                            (125, 'Liberia'),
                            (126, 'Libia'),
                            (127, 'Liechtenstein'),
                            (128, 'Lituania'),
                            (129, 'Luxemburgo'),
                            (130, 'Macao'),
                            (131, 'ARY Macedonia'),
                            (132, 'Madagascar'),
                            (133, 'Malasia'),
                            (134, 'Malawi'),
                            (135, 'Maldivas'),
                            (136, 'Malí'),
                            (137, 'Malta'),
                            (138, 'Islas Malvinas'),
                            (139, 'Islas Marianas del Norte'),
                            (140, 'Marruecos'),
                            (141, 'Islas Marshall'),
                            (142, 'Martinica'),
                            (143, 'Mauricio'),
                            (144, 'Mauritania'),
                            (145, 'Mayotte'),
                            (146, 'México'),
                            (147, 'Micronesia'),
                            (148, 'Moldavia'),
                            (149, 'Mónaco'),
                            (150, 'Mongolia'),
                            (151, 'Montserrat'),
                            (152, 'Mozambique'),
                            (153, 'Myanmar'),
                            (154, 'Namibia'),
                            (155, 'Nauru'),
                            (156, 'Nepal'),
                            (157, 'Nicaragua'),
                            (158, 'Níger'),
                            (159, 'Nigeria'),
                            (160, 'Niue'),
                            (161, 'Isla Norfolk'),
                            (162, 'Noruega'),
                            (163, 'Nueva Caledonia'),
                            (164, 'Nueva Zelanda'),
                            (165, 'Omán'),
                            (166, 'Países Bajos'),
                            (167, 'Pakistán'),
                            (168, 'Palau'),
                            (169, 'Palestina'),
                            (170, 'Panamá'),
                            (171, 'Papúa Nueva Guinea'),
                            (172, 'Paraguay'),
                            (173, 'Perú'),
                            (174, 'Islas Pitcairn'),
                            (175, 'Polinesia Francesa'),
                            (176, 'Polonia'),
                            (177, 'Portugal'),
                            (178, 'Puerto Rico'),
                            (179, 'Qatar'),
                            (180, 'Reino Unido'),
                            (181, 'Reunión'),
                            (182, 'Ruanda'),
                            (183, 'Rumania'),
                            (184, 'Rusia'),
                            (185, 'Sahara Occidental'),
                            (186, 'Islas Salomón'),
                            (187, 'Samoa'),
                            (188, 'Samoa Americana'),
                            (189, 'San Cristóbal y Nevis'),
                            (190, 'San Marino'),
                            (191, 'San Pedro y Miquelón'),
                            (192, 'San Vicente y las Granadinas'),
                            (193, 'Santa Helena'),
                            (194, 'Santa Lucía'),
                            (195, 'Santo Tomé y Príncipe'),
                            (196, 'Senegal'),
                            (197, 'Serbia y Montenegro'),
                            (198, 'Seychelles'),
                            (199, 'Sierra Leona'),
                            (200, 'Singapur'),
                            (201, 'Siria'),
                            (202, 'Somalia'),
                            (203, 'Sri Lanka'),
                            (204, 'Suazilandia'),
                            (205, 'Sudáfrica'),
                            (206, 'Sudán'),
                            (207, 'Suecia'),
                            (208, 'Suiza'),
                            (209, 'Surinam'),
                            (210, 'Svalbard y Jan Mayen'),
                            (211, 'Tailandia'),
                            (212, 'Taiwán'),
                            (213, 'Tanzania'),
                            (214, 'Tayikistán'),
                            (215, 'Territorio Británico del Océano Índico'),
                            (216, 'Territorios Australes Franceses'),
                            (217, 'Timor Oriental'),
                            (218, 'Togo'),
                            (219, 'Tokelau'),
                            (220, 'Tonga'),
                            (221, 'Trinidad y Tobago'),
                            (222, 'Túnez'),
                            (223, 'Islas Turcas y Caicos'),
                            (224, 'Turkmenistán'),
                            (225, 'Turquía'),
                            (226, 'Tuvalu'),
                            (227, 'Ucrania'),
                            (228, 'Uganda'),
                            (229, 'Uruguay'),
                            (230, 'Uzbekistán'),
                            (231, 'Vanuatu'),
                            (232, 'Venezuela'),
                            (233, 'Vietnam'),
                            (234, 'Islas Vírgenes Británicas'),
                            (235, 'Islas Vírgenes de los Estados Unidos'),
                            (236, 'Wallis y Futuna'),
                            (237, 'Yemen'),
                            (238, 'Yibuti'),
                            (239, 'Zambia'),
                            (240, 'Zimbabue');
                        ");

        DB::table('atl_provincias')
            ->where('id_Pais', 1)
            ->update(['id_Pais' => 13]);
    }
}