<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciasParaguaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pais = App\Pais::where('nombre', 'Paraguay')->first();

        $listado_divisiones = [
            'Distrito Capital' => [
                'Asunción',
            ],
            'Concepción' => [
                'Arroyito',
                'Azotey',
                'Belén',
                'Concepción',
                'Horqueta',
                'Loreto',
                'San Carlos del Apa',
                'San Lázaro',
                'Yby Yaú',
                'Sargento José Félix López',
                'San Alfredo',
            ],
            'San Pedro' => [
                'Antequera',
                'Capiibary',
                'Choré',
                'General Elizardo Aquino',
                'General Isidoro Resquín',
                'Guayaibí',
                'Itacurubí del Rosario',
                'Liberación',
                'Lima',
                'Nueva Germania',
                'San Estanislao',
                'San Pablo',
                'San Pedro del Ycuamandiyú',
                'San Vicente Pancholo',
                'Santa Rosa del Aguaray',
                'Tacuatí',
                'Unión',
                'Veinticinco de Diciembre',
                'Villa del Rosario',
                'Yataity del Norte',
                'Yrybucuá',
            ],
            'Cordillera' => [
                'Altos',
                'Arroyos y Esteros',
                'Atyrá',
                'Caacupé',
                'Caraguatay',
                'Emboscada',
                'Eusebio Ayala',
                'Isla Pucú',
                'Itacurubí de la Cordillera',
                'Juan de Mena',
                'Loma Grande',
                'Mbocayaty del Yhaguy',
                'Nueva Colombia',
                'Piribebuy',
                'Primero de Marzo',
                'San Bernardino',
                'San José Obrero',
                'Santa Elena',
                'Tobatí',
                'Valenzuela',
            ],
            'Guairá' => [
                'Borja',
                'Coronel Martínez',
                'Dr. Bottrell',
                'Fassardi',
                'Félix Pérez Cardozo',
                'Garay',
                'Colonia Independencia',
                'Itapé',
                'Iturbe',
                'Mbocayaty',
                'Natalicio Talavera',
                'Ñumí',
                'Paso Yobái',
                'San Salvador',
                'Tebicuary',
                'Troche',
                'Villarrica',
                'Yataity',
            ],
            'Caaguazú' => [
                'Caaguazú',
                'Carayaó',
                'Coronel Oviedo',
                'Doctor Cecilio Báez',
                'Doctor J. Eulogio Estigarribia',
                'Doctor Juan Manuel Frutos',
                'José Domingo Ocampos',
                'La Pastora',
                'Mcal. Francisco S. López',
                'Nueva Londres',
                'Nueva Toledo',
                'Raúl Arsenio Oviedo',
                'Repatriación',
                'R. I. Tres Corrales',
                'San Joaquín',
                'San José de los Arroyos',
                'Santa Rosa del Mbutuy',
                'Simón Bolívar',
                'Tembiaporá',
                'Tres de Febrero',
                'Vaquería',
                'Yhú',
            ],
            'Caazapá' => [
                'Tres de Mayo',
                'Abaí',
                'Buena Vista',
                'Caazapá',
                'Doctor Moisés S. Bertoni',
                'Fulgencio Yegros',
                'General Higinio Morínigo',
                'Maciel',
                'San Juan Nepomuceno',
                'Tavaí',
                'Yuty',
            ],
            'Itapúa' => [
                'Alto Verá',
                'Bella Vista',
                'Cambyretá',
                'Capitán Meza',
                'Capitán Miranda',
                'Carlos Antonio López',
                'Carmen del Paraná',
                'Coronel Bogado',
                'Edelira',
                'Encarnación',
                'Fram',
                'General Artigas',
                'General Delgado',
                'Hohenau',
                'Itapúa Poty',
                'Jesús',
                'La Paz',
                'José Leandro Oviedo',
                'Mayor Otaño',
                'Natalio',
                'Nueva Alborada',
                'Obligado',
                'Pirapó',
                'San Cosme y Damián',
                'San Juan del Paraná',
                'San Pedro del Paraná',
                'San Rafael del Paraná',
                'Tomás Romero Pereira',
                'Trinidad',
                'Yatytay',
            ],
            'Misiones' => [
                'Ayolas',
                'San Ignacio',
                'San Juan Bautista.',
                'San Miguel',
                'San Patricio',
                'Santa María',
                'Santa Rosa',
                'Santiago',
                'Villa Florida',
                'Yabebyry',
            ],
            'Paraguarí' => [
                'Acahay',
                'Caapucú',
                'Carapeguá',
                'Escobar',
                'Gral. Bernardino Caballero',
                'La Colmena',
                'María Antonia',
                'Mbuyapey',
                'Paraguarí',
                'Pirayú',
                'Quiindy',
                'Quyquyhó',
                'San Roque González de Santa Cruz',
                'Sapucai',
                'Tebicuarymí',
                'Yaguarón',
                'Ybycuí',
                'Ybytymí',
            ],
            'Alto Paraná' => [
                'Ciudad del Este',
                'Doctor Juan León Mallorquín',
                'Doctor Raúl Peña',
                'Domingo Martínez de Irala',
                'Hernandarias',
                'Iruña',
                'Itakyry',
                'Juan Emilio O\'Leary',
                'Los Cedrales',
                'Mbaracayú',
                'Minga Guazú',
                'Minga Porá',
                'Naranjal',
                'Ñacunday',
                'Presidente Franco',
                'San Alberto',
                'San Cristóbal',
                'Santa Fe del Paraná',
                'Santa Rita',
                'Santa Rosa del Monday',
                'Tavapy',
                'Yguazú',
            ],
            'Central' => [
                'Areguá',
                'Capiatá',
                'Fernando de la Mora',
                'Guarambaré',
                'Itá',
                'Itauguá',
                'Julián Augusto Saldívar',
                'Lambaré',
                'Limpio',
                'Luque',
                'Mariano Roque Alonso',
                'Ñemby',
                'Nueva Italia',
                'San Antonio',
                'San Lorenzo',
                'Villa Elisa',
                'Villeta',
                'Ypacaraí',
                'Ypané',
            ],
            'Ñeembucú' => [
                'Alberdi',
                'Cerrito',
                'Desmochados',
                'General José Eduvigis Díaz',
                'Guazú Cuá',
                'Humaitá',
                'Isla Umbú',
                'Laureles',
                'Mayor José J. Martínez',
                'Paso de Patria',
                'Pilar',
                'San Juan Bautista del Ñeembucú',
                'Tacuaras',
                'Villa Franca',
                'Villalbín',
                'Villa Oliva',
            ],
            'Amambay' => [
                'Bella Vista',
                'Capitán Bado',
                'Pedro Juan Caballero',
                'Zanja Pytá',
                'Karapaí',
            ],
            'Canindeyú' => [
                'Corpus Christi',
                'Curuguaty',
                'Gral. Francisco Caballero Álvarez',
                'Itanará',
                'Katueté',
                'La Paloma',
                'Maracaná',
                'Nueva Esperanza',
                'Puerto Adela',
                'Salto del Guairá',
                'Villa Ygatimí',
                'Yasy Cañy',
                'Ybyrarovaná',
                'Ypejhú',
                'Yby Pytá',
            ],
            'Presidente Hayes' => [
                'Benjamín Aceval',
                'Dr. José Falcón',
                'General José María Bruguez',
                'Nanawa',
                'Puerto Pinasco',
                'Tte. Irala Fernández',
                'Tte. Esteban Martínez',
                'Villa Hayes',
            ],
            'Alto Paraguay' => [
                'Bahía Negra',
                'Capitán Carmelo Peralta',
                'Puerto Casado',
                'Fuerte Olimpo',
            ],
            'Boquerón' => [
                'Filadelfia',   
                'Loma Plata',   
                'Mariscal Estigarribia',    
            ],
        ];

        foreach ($listado_divisiones as $k => $v) {
            $p = new App\Provincia;
            $p->provincia = $k;
            $p->id_pais = $pais->id;
            $p->save();

            foreach ($v as $vv) {
                $s = new App\Localidad;
                $s->localidad = $vv;
                $s->id_provincia = $p->id;
                $s->save();
            }
        }

    }
}