ALTER TABLE `sigp`.`Persona` 
DROP COLUMN `verificado`,
DROP COLUMN `Barrio_Vecino`,
DROP COLUMN `Vecino_Voluntario`,
DROP COLUMN `idAreaEstudio`,
DROP COLUMN `idCarrera`,
DROP COLUMN `dispHoraria`,
DROP COLUMN `ultimaActualizacion`,
DROP COLUMN `ultimaEntrada`,
DROP COLUMN `fechaInscripcion`,
DROP COLUMN `dpto`,
DROP COLUMN `piso`,
DROP COLUMN `numero`,
DROP COLUMN `calle`,
DROP COLUMN `idRegionLT`,
DROP COLUMN `terminosVoluntarioMasivo`,
DROP COLUMN `terminosVoluntarioPermanente`,
DROP COLUMN `idEmpresa`,
DROP COLUMN `configuracion`,
DROP COLUMN `captacion`,
DROP COLUMN `lenguaje`,
DROP COLUMN `statusCTCT`,
DROP COLUMN `idContactoCTCT`,
DROP COLUMN `nuevaPortada`,
DROP COLUMN `loginMailUTPMP`,
DROP COLUMN `loginActiveDirectory`,
DROP COLUMN `anoEstudio`,
DROP COLUMN `carrera`,
DROP COLUMN `universidad_string`,
DROP COLUMN `idColegio`,
DROP COLUMN `idUniversidad`,
DROP COLUMN `idCiudad`,
DROP COLUMN `idPaisResidencia`,
DROP INDEX `ix_Persona_DniPais` ,
ADD INDEX `ix_Persona_DniPais` (`dni` ASC),
DROP INDEX `Persona_ibfk_5_idx` ,
DROP INDEX `fk_Persona_Carrera_idx` ,
DROP INDEX `fk_Persona_RegionLT_idx` ,
DROP INDEX `fk_Persona_Colegio` ,
DROP INDEX `fk_Persona_Universidad` ,
DROP INDEX `Persona_ibfk_4` ,
DROP INDEX `idCiudad` ,
DROP INDEX `idPaisResidencia` ;