ALTER TABLE `sigp`.`Actividad` 
DROP COLUMN `CaptacionesUL`,
DROP COLUMN `PuntosEnvioUL`,
DROP COLUMN `LinkPago`,
DROP COLUMN `CostoConMoneda`,
DROP COLUMN `MailPago`,
DROP COLUMN `EnviarMailPago`,
DROP COLUMN `destacada`,
DROP COLUMN `mailSeguimiento`,
DROP COLUMN `statusMailSeguimiento`,
DROP COLUMN `linkFormularioEvaluacion`,
DROP COLUMN `idZona`,
DROP COLUMN `idAsentamiento`,
DROP COLUMN `idFormulario`,
DROP COLUMN `mailBeca`,
DROP COLUMN `pAcompanantePost`,
DROP COLUMN `captaciones`,
DROP COLUMN `puntosEnvio`,
DROP COLUMN `estadoDefault`,
DROP COLUMN `idEmpresa`,
DROP COLUMN `inscripcion`,
DROP COLUMN `presupuesto`,
DROP COLUMN `mostrarFB`,
DROP COLUMN `idListaCTCT`,
DROP COLUMN `compromiso`,
DROP COLUMN `actividadSecundaria`,
DROP COLUMN `enviarMail`,
DROP COLUMN `tPortugues`,
DROP COLUMN `pAcompanante`,
DROP COLUMN `pAnoEstudio`,
DROP COLUMN `pCarrera`,
DROP COLUMN `pUniversidad`,
DROP COLUMN `pFonoMovil`,
DROP COLUMN `pDNI`,
DROP COLUMN `pApMat`,
DROP COLUMN `numConstruccion`,
DROP COLUMN `idEncuestaDinamica`,
DROP COLUMN `idPrograma`,
DROP COLUMN `tipoConstruccion`,
DROP COLUMN `comentarios`,
DROP COLUMN `casasConstruidas`,
DROP COLUMN `casasPlanificadas`,
DROP COLUMN `fechaInicioFinFormato`,
DROP INDEX `fk_Actividad_1_idx1` ,
DROP INDEX `Actividad_ibfk_9_idx` ,
DROP INDEX `Actividad_ibfk_8_idx` ,
DROP INDEX `Actividad_ibfk_7` ,
DROP INDEX `idPrograma` ;
