ALTER TABLE `sigp`.`Inscripcion` 
DROP COLUMN `idAreadeInteres`,
DROP COLUMN `fechaSubsidio`,
DROP COLUMN `captacion`,
DROP COLUMN `puntoEnvio`,
DROP COLUMN `idRazonSubsidio`,
DROP COLUMN `subsidio`,
DROP COLUMN `comentarios`,
DROP COLUMN `acompanante`,
DROP COLUMN `aceptarCompromiso`,
DROP COLUMN `evaluacion`,
DROP COLUMN `fechaFin`,
DROP COLUMN `idLocalidadRol`,
DROP COLUMN `idMesaTrabajoLTRol`,
DROP COLUMN `idProgramaRol`,
DROP COLUMN `idMesaTrabajoRol`,
DROP COLUMN `idActividadRol`,
DROP COLUMN `idCuadrillaRol`,
DROP COLUMN `idEscuelaRol`,
DROP COLUMN `idUnidadOrganizacional`,
DROP INDEX `fk_Inscripcion_1_idx1` ,
DROP INDEX `Inscripcion_ibfk_45_idx` ,
DROP INDEX `idLocalidadRol` ,
DROP INDEX `idMesaTrabajoRol` ,
DROP INDEX `idMesaTrabajoLTRol` ,
DROP INDEX `idProgramaRol` ,
DROP INDEX `idUnidadOrganizacional` ,
DROP INDEX `idCuadrillaRol` ,
DROP INDEX `idEscuelaRol` ,
DROP INDEX `idActividadRol` ;
