<?php

return [
    'payu' => [
        'messages' => [
            'APPROVED' => '',
            'PAYMENT_NETWORK_REJECTED' => 'Transacción rechazada por entidad financiera',
            'ENTITY_DECLINED' => 'Transacción rechazada por el banco',
            'INSUFFICIENT_FUNDS' => 'Fondos insuficientes',
            'INVALID_CARD' => 'Tarjeta inválida',
            'CONTACT_THE_ENTITY' => 'Contactar entidad financiera',
            'BANK_ACCOUNT_ACTIVATION_ERROR' => 'Débito automático no permitido',
            'BANK_ACCOUNT_NOT_AUTHORIZED_FOR_AUTOMATIC_DEBIT' => 'Débito automático no permitido',
            'INVALID_AGENCY_BANK_ACCOUNT' => 'Débito automático no permitido',
            'INVALID_BANK_ACCOUNT' => 'Débito automático no permitido',
            'INVALID_BANK' => 'Débito automático no permitido',
            'EXPIRED_CARD' => '	Tarjeta vencida',
            'RESTRICTED_CARD' => 'Tarjeta restringida',
            'INVALID_EXPIRATION_DATE_OR_SECURITY_CODE' => 'Fecha de expiración o código de seguridad inválidos',
            'REPEAT_TRANSACTION' => 'Reintentar pago',
            'INVALID_TRANSACTION' => 'Transacción inválida',
            'EXCEEDED_AMOUNT' => '	El valor excede el máximo permitido por la entidad',
            'ABANDONED_TRANSACTION' => 'Transacción abandonada por el pagador',
            'CREDIT_CARD_NOT_AUTHORIZED_FOR_INTERNET_TRANSACTIONS' => 'Tarjeta no autorizada para comprar por internet',
            'ANTIFRAUD_REJECTED' => 'Transacción rechazada por sospecha de fraude',
            'DIGITAL_CERTIFICATE_NOT_FOUND' => 'Certificado digital no encontrado',
            'BANK_UNREACHABLE' => 'Error tratando de cominicarse con el banco',
            'ENTITY_MESSAGING_ERROR' => 'Error comunicándose con la entidad financiera',
            'NOT_ACCEPTED_TRANSACTION' => 'Transacción no permitida al tarjetahabiente',
            'INTERNAL_PAYMENT_PROVIDER_ERROR' => 'Error',
            'INACTIVE_PAYMENT_PROVIDER' => 'Error',
            'ERROR' => 'Error',
            'ERROR_CONVERTING_TRANSACTION_AMOUNTS' => 'Error',
            'FIX_NOT_REQUIRED' => 'Error',
            'AUTOMATICALLY_FIXED_AND_SUCCESS_REVERSAL' => 'Error',
            'AUTOMATICALLY_FIXED_AND_UNSUCCESS_REVERSAL' => 'Error',
            'AUTOMATIC_FIXED_NOT_SUPPORTED' => 'Error',
            'NOT_FIXED_FOR_ERROR_STATE' => 'Error',
            'ERROR_FIXING_AND_REVERSING' => 'Error',
            'ERROR_FIXING_INCOMPLETE_DATA' => 'Error',
            'PAYMENT_NETWORK_BAD_RESPONSE' => 'Error',
            'PAYMENT_NETWORK_NO_CONNECTION' => 'No fue posible establecer comunicación con la entidad financiera',
            'PAYMENT_NETWORK_NO_RESPONSE' => 'No se recibió respuesta de la entidad financiera',
            'EXPIRED_TRANSACTION' => 'Transacción expirada',
            'PENDING_TRANSACTION_REVIEW' => 'Transacción en validación manual',
            'PENDING_TRANSACTION_CONFIRMATION' => 'Recibo de pago generado. En espera de pago',
            'PENDING_TRANSACTION_TRANSMISSION' => 'Transacción no permitida',
            'PENDING_PAYMENT_IN_ENTITY' => 'Recibo de pago generado. En espera de pago',
            'PENDING_PAYMENT_IN_BANK' => '	Recibo de pago generado. En espera de pago',
            'PENDING_AWAITING_PSE_CONFIRMATION' => 'En espera de confirmación de PSE',
            'PENDING_NOTIFYING_ENTITY' => 'Recibo de pago generado. En espera de pago',
        ],
        'url' => 'https://sandbox.checkout.payulatam.com/ppp-web-gateway-payu/',
        'method' => 'POST'
    ]

];